spring:
  application:
    name: shopflow-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  default-produces-media-type: application/json
